### ISSUE TITLE
include a one-file solution

### ISSUE THREAD

**Issue by rubo77** [mattbit/mysql-compat#1]
can you put this into one file, like this?

https://gist.github.com/rubo77/1db052edd8d723b59c79790b42635f1e

And maybe add an install instriuctions in the README would be nice

**Comment by mattbit** [comment]
You’re right, the logic is a bit more involved than the mysqli replacement so it cannot fit into a single file, at the moment you can redeclare the old functions in this way:

``` php
use Mattbit\MysqlCompat\Mysql;

if (!function_exists("mysql_query")) {
    function mysql_query($query, $connection) {
        return Mysql::query($query, $connection);
    }
}
```

The installation is supposed to be done with composer, but at the moment package is still not published on packagist, so you have to load it directly from the repository as described here: https://getcomposer.org/doc/05-repositories.md#loading-a-package-from-a-vcs-repository

I don’t have much time these days, but I’ll try to add some info about installation and usage as soon as possible.

**Comment by pteague** [comment]
Do you want this inside 1 large `if (!function_exists("mysql_connect")) { ... }` or do you want each function wrapped with it's own?

**Comment by rubo77** [comment]
I think each in its own is cleaner, is it?

**Comment by mattbit** [comment]
I think it’s more tidy to keep all the functions in one file, each wrapped in a specific `if` (e.g. https://github.com/illuminate/support/blob/master/helpers.php). I would like to keep the replacement functions optional, too.
I’ll try to get something ready by tomorrow.

**Comment by pteague** [comment]
I'd asked as I already got a large file done, but I probably have the wrong method names for some. I'll finish wrapping each with it's individual if statement & submit a merge request.

**Comment by mattbit** [comment]
@pteague Have you seen my last commit https://github.com/mattbit/mysql-compat/commit/fd03003a21dcd8229a9200cb5df556169a923451?
This should work fine, could you confirm?

**Comment by rubo77** [comment]
this is a nice thing, but not the request here. I was looking for a file, that I could just include in my code like

require_once("one-file-solution.inc.php");

and all my lost functions are back ;)

**Comment by rubo77** [comment]
Ah cool, i see:

All you have to do now os to use the Mysql::defineGlobals method:

```
 require __DIR__ . '/vendor/autoload.php';
 Mattbit\MysqlCompat\Mysql::defineGlobals();
```

**Comment by mattbit** [comment]
@rubo77 Yes, just install it with composer and call `Mysql::defineGlobals()`.

**Comment by rubo77** [comment]
Can I use this with php only? so I can deploy this inside an opensource project? (without installation of anything?)

**Comment by mattbit** [comment]
@rubo77 you _can_ use composer (which is written in php and it’s an opensource project itself), it will make your life easier. You can follow the instructions [here](https://getcomposer.org/download/) to download composer.phar. Then just run `./composer.phar require mattbit/mysql-compat`.
